### ISSUE TITLE
Numeric component

### ISSUE THREAD

**Issue by DennyLoko** [phpol/phpol#16]
I'd like to put a `Numeric` component up for a vote.

This component should handle the formatting and casting of the numeric types. Initially, I'm planning to implement the `Integer` type, and later the `Float`.

If this component gets approval, I'll open another thread with the specification and details about the `Integer` implementation.

---

Voting should be :+1:, :-1: or self-declared abstentions.
Voting will close when all 7 voting members have cast their votes, or at February 9th 2017, at 16:03 BRST. If no minimum quorum (4 members) is met by then, the vote will fail and will have to be restarted.

**Comment by naroga** [comment]
A `numeric` data type is tricky. PHP has no operator overloading, which means Number(5) + Number(8) is unsolvable. Even the most basic operations (like adding, subtracting and others) would have to be done through class methods, and the overhead (and thus, the performance hit) would be enormous.

Operations with numbers are not procedural, they are declarative.

I'd rather have a `Math` component that encapsulates the most common math functions (like `pow`, `log`, etc) then have a `Numeric` component.

With a possible `Numeric` component, will we attempt to solve PHP's various rounding issues through bc_math functions? Will we take the chance to add more math functions, even if it's on userland?

**Comment by DennyLoko** [comment]
I thought about this numeric types not for math operations, but for formatting, like: `str_pad`, `number_format`, conversions to/from hex, etc...

Of course, it has the downside of trick the user to think that he can use this types to do math operations, but these operations I agree that should be handled in a `Math` component.

**Comment by lucasmezencio** [comment]
@DennyLoko I think that this component must be renamed to `Number`, take a look at this comment: https://github.com/phpol/phpol/issues/2#issuecomment-277746624

**Comment by filhocodes** [comment]
> A numeric data type is tricky. PHP has no operator overloading, which means Number(5) + Number(8) is unsolvable. Even the most basic operations (like adding, subtracting and others) would have to be done through class methods, and the overhead (and thus, the performance hit) would be enormous.

@naroga the problem: Is this library goal to "Wrap and Extend PHP in a Completely OOP Layer" (as said in #4, which is still open for discussion)? If this is the goal, makes more sense to create a numeric component instead of using primitive values.

Even if not, I agree that math functions should be part of a `math` component.

Also, I think the numeric component should contain abstractions for common values, like currency and memory size, or (in a more future-proof way) a base interface where developers can extend to create their values (example: distance, height, etc, whatever the software needs) with definitions like `radix` and `render formats`, and this interface should be allowed as parameters for components like `Math`.

**Comment by hernandev** [comment]
Numeric is a NO-GO

-IC suffix are intended to create adjectives.

Numeric makes much sense as Numericous..

We should not NAME things with adjectives

**Comment by DennyLoko** [comment]
@hernandev I agree that `Numeric` is an adjective. =)

Maybe I expressed myself wrong, but the main proposal here is to allocate the `Numeric` namespace to contain the numeric types, as `Integer`, `Float` and `Money`, and as a base to define how a numeric type should behave.

**Comment by naroga** [comment]
@marcossffilho

> @naroga the problem: Is this library goal to "Wrap and Extend PHP in a Completely OOP Layer" (as said in #4, which is still open for discussion)? If this is the goal, makes more sense to create a numeric component instead of using primitive values.

```cpp
int age = 10;
age++;
```
This is not procedural, this is declarative/expressive. 

```php
$age = Integer(10);
$age->increment();
```

The second snippet is no more OOP than the first one.

The issue with PHP is that most FUNCTIONS and language constructs are scattered in the global namespace. We aim to solve this by organizing, standardizing and extending the language in userland. However, EXPRESSIONS are not something to be ported. `$age = 10 + 5` is perfectly fine as is, and `$age = Integer(10)->add(Integer(5))` would be just unnecessary verbosity and overhead. 

In javascript, it makes sense to treat numbers as objects, because they can overload the math operations. `5.toPrecision(2)` is fine in javascript, because you can also do `5 + 3`. Now, in PHP, if we were to emulate this, we'd have `Number(5)->toPrecision(2)`, but we'd also need `Number(5)->add(Number(3))`, which creeps me out. Calling a function to perform basic math operation adds a LOT of overhead and verbosity.

I'll vote a solid NO for number/numeric data types, but I'll happily cast a YES vote for number-operation components, like `NumberFormatter` or something to that effect.

**Comment by pedrommone** [comment]
@DennyLoko I was going to YES, and then @naroga comes with a hammer and a town of things. He is right, in php userland thats cannot be done and would be a terrible overwhelm. 

Anyway, I'm going to vote YES for `NumberFormatter` or something. :)

**Comment by naroga** [comment]
This is a very relevant reference on the cost of php function calls: http://jpauli.github.io/2015/01/22/on-php-function-calls.html#performing-the-function-call

**Comment by naroga** [comment]
Sorry about the spam, but I'll leave this here.

Even JS, where everything is an object, won't allow `5.toPrecision(2)`. You need to assign the value to a variable in order to call its methods.

```javascript
5.toPrecision(2); //this is an error;
var a = 5;
a.toPrecision(2); //this is ok, because I did the boilerplate.
(5).toPrecision(2); //this is also ok, because idk
```

**Comment by DennyLoko** [comment]
I'm withdrawing this proposal.
A new one should be open with a  proposal of a `NumberFormatter`.

**Comment by lucasmezencio** [comment]
@DennyLoko can you close this issue, please?
